### ISSUE TITLE
stripe.customers.list().autoPaginateEach() is not a function

### ISSUE THREAD

**Issue by AshishkrGoyal** [stripe/stripe-node#536]
```node
stripe.customers.list(
    {
    limit:100,
    'created[gt]': '1541548800', //7-nov-2018
    'created[lt]': '1542153600'}) //14-nov-2018
    .autoPagingEach((customer) => {
        //console.log(startDate);
        //console.log(endDate);
    console.log(customer);
    count++;
    console.log(count);
}).then(() => {
    console.log('Done iterating.');
}).catch();
```

when i run this it give me an error that 
stripe.customers.list(...).autoPagingEach is not a function..

it is working fine before some time but now it throws this error!
Please look into this !

Thanks in advance !

**Comment by rattrayalex-stripe** [comment]
Hi @AshishkrGoyal ,

What is the result of `console.log(require('stripe').PACKAGE_VERSION)`?

Does this fail sporadically or did it recently start failing at all times? Does it work with other API's, like `stripe.products.list().autoPagingEach(console.log)`?

**Comment by robz-stripe** [comment]
I see that the title here mentions `autoPaginateEach()`, which is indeed not a function. The sample code is using `autoPagingEach()` which appears to work fine in my testing with `6.20.1`.
