### ISSUE TITLE
v22 - change to `generateTestHeaderString`

### ISSUE THREAD

**Issue by tsmithhisler** [stripe/stripe-node#2666]
### Describe the bug

After upgrading to v22, the shape of the input type for `generateTestHeaderString` now requires more properties.

The old manually defined type made all properties except payload and secret optional (https://github.com/stripe/stripe-node/blob/9c0a9cb7482d19c2e6e6b5b5574c1a2f0149a2a9/types/Webhooks.d.ts#L104).

The existing type that is now exported has all properties required (https://github.com/stripe/stripe-node/blob/master/src/Webhooks.ts#L30).

### To Reproduce

1. Look at test under webhook signing examples: https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/test/main.ts#L63
2. Compare options to type in Webhook.ts
3. Observe the following error:
```
error TS2345: Argument of type '{ payload: string; secret: string; }' is not assignable to parameter of type 'WebhookTestHeaderOptions'.
  Type '{ payload: string; secret: string; }' is missing the following properties from type 'WebhookTestHeaderOptions': timestamp, scheme, signature, cryptoProvider

116     const stripeSignature = stripe.webhooks.generateTestHeaderString({
                                                                         ~
117       payload: payloadString,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
118       secret: testWebhookSecret,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
119     });
```

### Expected behavior

I expect there to be no typescript error when calling `generateTestHeaderString` as the stripe example test does (or I can update my usage to include all other properties, but I would expect the stripe example test to do the same).

### OS

Linux (Arch, btw)

### Node version

Node v24.14.1

### Library version

stripe-node v22.0.0

### API version

latest

**Comment by prathmesh-stripe** [comment]
@tsmithhisler Apologies for the inconvenience on this. We shipped a fix for this in our latest [v22.0.2 release](https://github.com/stripe/stripe-node/releases/tag/v22.0.2).
