### ISSUE TITLE
TypeScript error when initializing Stripe client after upgrading to v22

### ISSUE THREAD

**Issue by itsjgf** [stripe/stripe-node#2660]
### Describe the bug

Hey,

After upgrading to **Stripe Node SDK v22**, Stripe initialization stopped working as expected.

### Code

```ts
import Stripe from 'stripe';
import config from '@/config';

const stripeClient = new Stripe(config.STRIPE_SECRET_KEY, {
  apiVersion: '2026-03-25.dahlia',
  maxNetworkRetries: 3,
});

export default stripeClient;
```

### Error

```txt
src/services/stripe/client.ts:4:22 - error TS7009:
'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.

4 const stripeClient = new Stripe(config.STRIPE_SECRET_KEY, {
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5   apiVersion: '2026-03-25.dahlia',
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6   maxNetworkRetries: 3,
  ~~~~~~~~~~~~~~~~~~~~~~~
7 });
```

### tsconfig.json

```json
{
  "ts-node": {
    "transpileOnly": true,
    "files": true,
    "require": ["@babel/register", "module-alias/register"]
  },
  "compilerOptions": {
    "lib": ["es2023"],
    "module": "commonjs",
    "target": "es2023",
    "allowJs": true,
    "checkJs": false,
    "outDir": "./dist",
    "noEmit": true,
    "verbatimModuleSyntax": false,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "paths": {
      "@/*": ["./src/*"],
      "@test/*": ["./test/*"]
    },
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true
  },
  "include": ["src", "test", "migrations", "plopfile.ts"]
}
```

### Additional context

* This exact code works correctly with **Stripe SDK v21.x**
* The issue appears immediately after upgrading to **v22**
* No changes were made to the TypeScript configuration

**Comment by crrobinson14** [comment]
Per the [Release Notes](https://github.com/stripe/stripe-node/releases/tag/v22.0.0) "Stripe import is now a true ES6 class. Use new Stripe() to create a StripeClient instead of calling it". The issue appears to be that that statement is not true, or at least a miscommunication. No import example is provided in the release notes, but if you change the import to `import {Stripe} from 'stripe';` on that class-import assumption you get "Only a void function can be called with the new keyword.".

**Comment by prathmesh-stripe** [comment]
Are you using CommonJS? Can you share your package.json file and maybe the TypeScript version.

**Comment by itsjgf** [comment]
@prathmesh-stripe here's the package.json (I stripped everything that is not related to the issue). 

Typescript version: 5.9.3

```

{
  "private": true,
  "main": "src/index.ts",
  "scripts": {
    "typecheck": "tsc"
  },
  "dependencies": {
    "express": "5.2.1",
    "stripe": "21.0.1",
    "typescript": "5.9.3",
    "ts-node": "10.9.2"
  },
  "packageManager": "pnpm@10.33.0"
}
```
The exact setup works as expected in the previous version (21)

**Comment by prathmesh-stripe** [comment]
Thanks for flagging this issue. We have shipped a fix for this in [v22.0.1](https://github.com/stripe/stripe-node/releases/tag/v22.0.1) patch. You should now be able to initialize StripeClient properly in your TypeScript project.

**Comment by itsjgf** [comment]
@prathmesh-stripe it seems to be working now, but it looks like the TypeScript types are no longer being exported.

Even basic usage like this does not work anymore:

```ts
import type Stripe from 'stripe';

const customer: Stripe.Customer;
```


What's the recommended aproach now? I can open a new PR if that's needed.
